platform :osx, '10.15'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)

    # Bump deployment target (pods use 10.11/10.12, Xcode 26 requires 10.13+)
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.15'
    end

    # Fix BoringSSL-GRPC: Xcode 16+ rejects -GCC_WARN_INHIBIT_ALL_WARNINGS (shows as -G)
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end

  # Fix gRPC-Core and gRPC-C++: Xcode 16+ template parsing (CallSeqFactory)
  ['gRPC-Core', 'gRPC-C++'].each do |pod_name|
    grpc_basic_seq = File.join(installer.sandbox.root, pod_name, 'src', 'core', 'lib', 'promise', 'detail', 'basic_seq.h')
    if File.exist?(grpc_basic_seq)
      contents = File.read(grpc_basic_seq)
      if contents.include?('Traits::template CallSeqFactory(f_, *cur_, std::move(arg))')
        File.write(grpc_basic_seq, contents.gsub(
          'Traits::template CallSeqFactory(f_, *cur_, std::move(arg))',
          'Traits::template CallSeqFactory<>(f_, *cur_, std::move(arg))'
        ))
      end
    end
  end
end
