// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhqi4lgpThH2CM-k2DOug0QRIubcAbIk0',
    appId: '1:221559958002:web:c5f90795c1a8ccc38a236b',
    messagingSenderId: '221559958002',
    projectId: 'on-the-way-rebuild',
    authDomain: 'on-the-way-rebuild.firebaseapp.com',
    storageBucket: 'on-the-way-rebuild.firebasestorage.app',
    measurementId: 'G-GBECLLNT9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuiE-A7fQ7SevOgujokZt2ABY4DiFGXEg',
    appId: '1:221559958002:android:872f6bf5d27afe6d8a236b',
    messagingSenderId: '221559958002',
    projectId: 'on-the-way-rebuild',
    storageBucket: 'on-the-way-rebuild.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA52EuZ1M4zygMj4u17FO7XVcKRTit_-lk',
    appId: '1:221559958002:ios:1492e69cb03e68828a236b',
    messagingSenderId: '221559958002',
    projectId: 'on-the-way-rebuild',
    storageBucket: 'on-the-way-rebuild.firebasestorage.app',
    iosBundleId: 'com.joshua.otwApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA52EuZ1M4zygMj4u17FO7XVcKRTit_-lk',
    appId: '1:221559958002:ios:1492e69cb03e68828a236b',
    messagingSenderId: '221559958002',
    projectId: 'on-the-way-rebuild',
    storageBucket: 'on-the-way-rebuild.firebasestorage.app',
    iosBundleId: 'com.joshua.otwApp',
  );

}